In [1]:
import numpy as np

a = np.random.randn(5)

print (a)

[ 1.45225535  0.12849474  0.74460666  2.44434753 -0.65617761]


In [4]:
print(a.shape) # rank  1 array dont use it.

(5,)


In [5]:
print(a.T)

[ 1.45225535  0.12849474  0.74460666  2.44434753 -0.65617761]


In [6]:
print(np.dot(a,a.T))

9.085399461621398


In [10]:
a = np.random.randn(5,1)
print(a)

[[ 0.47819321]
 [ 0.38026783]
 [ 0.86066494]
 [ 0.29222504]
 [-0.29634924]]


In [11]:
print(np.dot(a,a.T))


[[ 0.22866874  0.18184149  0.41156413  0.13974003 -0.14171219]
 [ 0.18184149  0.14460362  0.32728319  0.11112378 -0.11269208]
 [ 0.41156413  0.32728319  0.74074415  0.25150785 -0.2550574 ]
 [ 0.13974003  0.11112378  0.25150785  0.08539548 -0.08660067]
 [-0.14171219 -0.11269208 -0.2550574  -0.08660067  0.08782287]]


In [13]:
assert(a.shape == (5,1))

print()

[[ 0.33049118]
 [ 0.79179753]
 [ 0.10201286]
 [-1.1660831 ]
 [-0.83252915]
 [ 1.15645893]
 [ 0.57323793]
 [ 0.11783858]]
