In [2]:
import numpy as np

x = np.arange(8).reshape(8, 1)

candidates = [
    (2, 4, 4),
    (2, 2, 2),
    (1, 4, 3),
    (-1, 3),
]

for shape in candidates:
    try:
        y = x.reshape(shape)
        print(f"reshape{shape} -> OK, result shape: {y.shape}")
    except Exception as e:
        print(f"reshape{shape} -> Error: {e}")

reshape(2, 4, 4) -> Error: cannot reshape array of size 8 into shape (2,4,4)
reshape(2, 2, 2) -> OK, result shape: (2, 2, 2)
reshape(1, 4, 3) -> Error: cannot reshape array of size 8 into shape (1,4,3)
reshape(-1, 3) -> Error: cannot reshape array of size 8 into shape (3)


In [6]:
a = np.random.randn(3,4,5)

print(a)

print("shape ", a.shape)

print("reshapre to (12,5) ", a.reshape(12,5))


[[[ 0.98919542 -0.46978864  0.14858135 -0.57428838 -0.65138113]
  [-0.97812337  1.12014549  2.14855798 -1.30965563  1.85968594]
  [ 0.45205479  1.46925691  0.03958226  1.00384377 -0.09807045]
  [-0.80466306 -0.57321529  0.68626419  1.86943206 -3.30751461]]

 [[ 0.78525609 -0.003462    0.42607032 -0.55264289  0.15251516]
  [ 0.6163931   0.7744062  -1.11476939  0.84678315 -1.76567989]
  [-0.26038355  0.14022044  1.82841267 -0.48223011 -0.57517204]
  [-0.50392535  1.18275841  0.30145984 -0.58572762 -0.01309814]]

 [[-0.30034749  0.98275458 -0.57900452  1.706894   -1.64986651]
  [ 1.56033525  0.37040444  0.01787776 -0.03751059 -2.61364262]
  [ 1.08585841 -0.82056972  0.28432948 -1.8802015   1.30249514]
  [ 0.95571527 -2.96900251  0.22509532 -1.86230941 -0.47134757]]]
shape  (3, 4, 5)
reshapre to (12,5)  [[ 0.98919542 -0.46978864  0.14858135 -0.57428838 -0.65138113]
 [-0.97812337  1.12014549  2.14855798 -1.30965563  1.85968594]
 [ 0.45205479  1.46925691  0.03958226  1.00384377 -0.09807045]


In [8]:
# python
import numpy as np

x = np.arange(8)[:, None]   # shape (8, 1)
candidates = [(2, 2, 2), (8,), (1, 8), (-1, 3)]

for s in candidates:
    try:
        y = x.reshape(s)
        print("reshape", s, "-> OK, shape:", y.shape)
    except Exception as e:
        print("reshape", s, "-> Error:", e)

reshape (2, 2, 2) -> OK, shape: (2, 2, 2)
reshape (8,) -> OK, shape: (8,)
reshape (1, 8) -> OK, shape: (1, 8)
reshape (-1, 3) -> Error: cannot reshape array of size 8 into shape (3)


In [10]:
    import numpy as np
    arr = np.array([1, 2, 3, 4, 5, 6])
    new_arr = arr.reshape(2, 3)
    print(new_arr)
    # Output: [[1 2 3]
    #          [4 5 6]]

[[1 2 3]
 [4 5 6]]


In [13]:
a=np.random.randn(1,3) # a.shape=(1,3)a.shape=(1,3)

b=np.random.randn(3,3) # b.shape=(3,3)b.shape=(3,3)

c=np.dot(a,b) # c.shape=(1,3)c.shape=(1,3)

print (c)

[[0.7586442  0.23462587 0.27811535]]


In [14]:
# python
import numpy as np

np.random.seed(0)
A = np.random.randn(3, 3)   # shape (3,3)
v = np.random.randn(3, 1)   # shape (3,1)

# element-wise with broadcasting
C_elem = A * v

# matrix multiplication
C_dot = np.dot(A, v)

print("A.shape =", A.shape)
print("v.shape =", v.shape)
print("A * v -> shape:", C_elem.shape)
print(C_elem)
print("np.dot(A, v) -> shape:", C_dot.shape)
print(C_dot)

# quick checks
assert C_elem.shape == (3, 3)
assert C_dot.shape == (3, 1)


A.shape = (3, 3)
v.shape = (3, 1)
A * v -> shape: (3, 3)
[[ 0.72431725  0.16430395  0.40186835]
 [ 0.32278626  0.26900972 -0.1407706 ]
 [ 1.38168841 -0.22011478 -0.15010844]]
np.dot(A, v) -> shape: (3, 1)
[[ 2.20531004]
 [-0.23211222]
 [ 0.21819441]]


In [16]:
a=np.array([[2,1],[1,3]])

print(a * a)

[[4 1]
 [1 9]]


In [18]:
data = np.arange(12)
print(f"array original: {data}")
print(f"data shape original: {data.shape}")

array original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
data shape original: (12,)
